---
title: "CodeBook"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
All the variables, except `subject` and `activity` are normalized and bounded within [-1,1].

  
####  [1] "subject"                              
  
 **Values:** [1,30] 
  
 **Description:** ID of the volunteer subject who carried the experiment.
  
####  [2] "activity"                             
  
 **Values:** [WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING ,LAYING]
  
 **Description:** Activity performed by the person (subject)
  
####  [3] "timeBodyAccelerationMeanX"            
  
 **Values:** [-1,1] 
  
 **Description:**  Mean of the time body acceleration on the X axis.
  
####  [4] "timeBodyAccelerationMeanY"            
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body acceleration on the Y axis.
  
####  [5] "timeBodyAccelerationMeanZ"            
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body acceleration on the Z axis.
  
####  [6] "timeGravityAccelerationMeanX"         
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time gravity acceleration on the X axis.
  
####  [7] "timeGravityAccelerationMeanY"         
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time gravity acceleration on the Y axis.
  
####  [8] "timeGravityAccelerationMeanZ"         
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time gravity acceleration on the Z axis.
  
####  [9] "timeBodyAccelerationJerkMeanX"        
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body acceleration jerk signal on the X axis.
  
#### [10] "timeBodyAccelerationJerkMeanY"        
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body acceleration jerk signal on the Y axis.
  
#### [11] "timeBodyAccelerationJerkMeanZ"        
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body acceleration jerk signal on the Z axis.
  
#### [12] "timeBodyGyroscopeMeanX"               
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body gyroscope on the X axis.
  
#### [13] "timeBodyGyroscopeMeanY"               
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body gyroscope on the Y axis.
  
#### [14] "timeBodyGyroscopeMeanZ"               
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body gyroscope on the Z axis.
  
#### [15] "timeBodyGyroscopeJerkMeanX"           
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body gyroscope jerk signal on the X axis.
  
#### [16] "timeBodyGyroscopeJerkMeanY"           
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body gyroscope jerk signal on the Y axis.
  
#### [17] "timeBodyGyroscopeJerkMeanZ"           
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body gyroscope jerk signal on the Z axis.
  
#### [18] "timeBodyAccelerationMagnitudeMean"
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body acceleration .
  
#### [19] "timeGravityAccelerationMagnitudeMean" 
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time gravity.
  
#### [20] "timeBodyAccelerationJerkMagnitudeMean"
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body acceleration jerk signal.
  
#### [21] "timeBodyGyroscopeMagnitudeMean"       
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body gyroscope .
  
#### [22] "timeBodyGyroscopeJerkMagnitudeMean"   
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the time body gyroscope jerk signal.
  
#### [23] "freqBodyAccelerationMeanX"            
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the frequency body acceleration on the X axis.
  
#### [24] "freqBodyAccelerationMeanY"            
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the frequency body acceleration on the Y axis
  
#### [25] "freqBodyAccelerationMeanZ"            
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the frequency body acceleration on the Z axis
  
#### [26] "freqBodyAccelerationJerkMeanX"        
  
 **Values:** [-1,1] 
  
 **Description:** Frequency of the body acceleration jerk signal on the X axis.
  
#### [27] "freqBodyAccelerationJerkMeanY"        
  
 **Values:** [-1,1] 
  
 **Description:** Frequency of the body acceleration jerk signal on the Y axis.
  
#### [28] "freqBodyAccelerationJerkMeanZ"        
  
 **Values:** [-1,1] 
  
 **Description:** Frequency of the body acceleration jerk signal on the Z axis.
  
#### [29] "freqBodyGyroscopeMeanX"               
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the frequency body gyroscope on the x axis
  
#### [30] "freqBodyGyroscopeMeanY"               
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the frequency body acceleration on the x axis
  
#### [31] "freqBodyGyroscopeMeanZ"               
  
 **Values:** [-1,1] 
  
 **Description:** Mean of the frequency body acceleration on the x axis
  
#### [32] "freqBodyAccelerationMagnitudeMean"    
  
 **Values:** [-1,1] 
  
 **Description:** Frequency of the acceleration mean.
  
#### [33] "freqBodyAccelerationJerkMagnitudeMean"
  
 **Values:** [-1,1] 
  
 **Description:** Frequency of the acceleration jerk signal mean.
  
#### [34] "freqBodyGyroscopeMagnitudeMean"       
  
 **Values:** [-1,1] 
  
 **Description:** Frequency of the body gyroscope mean.
  
#### [35] "freqBodyGyroscopeJerkMagnitudeMean"   
  
 **Values:** [-1,1] 
  
 **Description:** Frequency of the body gyroscope jerk signal mean.
  
#### [36] "timeBodyAccelerationStdX"             
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [37] "timeBodyAccelerationStdY"             
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [38] "timeBodyAccelerationStdZ"             
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [39] "timeGravityAccelerationStdX"          
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [40] "timeGravityAccelerationStdY"          
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [41] "timeGravityAccelerationStdZ"          
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [42] "timeBodyAccelerationJerkStdX"         
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [43] "timeBodyAccelerationJerkStdY"         
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [44] "timeBodyAccelerationJerkStdZ"         
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [45] "timeBodyGyroscopeStdX"                
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [46] "timeBodyGyroscopeStdY"                
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [47] "timeBodyGyroscopeStdZ"                
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [48] "timeBodyGyroscopeJerkStdX"            
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [49] "timeBodyGyroscopeJerkStdY"            
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [50] "timeBodyGyroscopeJerkStdZ"            
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [51] "timeBodyAccelerationMagnitudeStd"     
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [52] "timeGravityAccelerationMagnitudeStd"  
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [53] "timeBodyAccelerationJerkMagnitudeStd" 
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [54] "timeBodyGyroscopeMagnitudeStd"        
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [55] "timeBodyGyroscopeJerkMagnitudeStd"    
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [56] "freqBodyAccelerationStdX"             
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [57] "freqBodyAccelerationStdY"             
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [58] "freqBodyAccelerationStdZ"             
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [59] "freqBodyAccelerationJerkStdX"         
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [60] "freqBodyAccelerationJerkStdY"         
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [61] "freqBodyAccelerationJerkStdZ"         
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [62] "freqBodyGyroscopeStdX"                
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [63] "freqBodyGyroscopeStdY"                
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [64] "freqBodyGyroscopeStdZ"                
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [65] "freqBodyAccelerationMagnitudeStd"     
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [66] "freqBodyAccelerationJerkMagnitudeStd" 
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [67] "freqBodyGyroscopeMagnitudeStd"        
  
 **Values:** [-1,1] 
  
 **Description:** Standard deviation of the time body acceleration on the x axis.
  
#### [68] "freqBodyGyroscopeJerkMagnitudeStd"
  
 **Values:** [-1,1]
  
 **Description:** Standard deviation of the time body acceleration on the x axis.